version: '3'
volumes:
  avito_volume01:

services:
  app:
    build: .
    networks:
      - spring
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8082:8082"
    links:
      - "redis"
    volumes:
      - avito_volume01:/home/kgenov/avito/avito:ro

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis
    networks:
      - spring

networks:
  spring:
    external: true